apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - image: com.petcare/eureka-server:0.0.1-SNAPSHOT
          name: eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
