apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.service.nodeport.port: "30002"
    kompose.service.type: NodePort
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: postgresqldb
  name: postgresqldb
spec:
  ports:
    - name: "5432"
      nodePort: 30002
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgresqldb
  type: NodePort
