apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: reservation-service
  name: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reservation-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: reservation-service
    spec:
      containers:
        - image: com.petcare/reservation-service:0.0.1-SNAPSHOT
          name: reservation-service
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
