apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: datagen
  name: datagen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datagen
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: datagen
    spec:
      containers:
        - args:
            - java
            - -classpath
            - /opt/datagen/flink-sql-demo.jar
            - myflink.SourceGenerator
            - --input
            - /opt/datagen/user_behavior.log
            - --output
            - kafka
            - kafka:9092
            - --speedup
            - "2000"
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka
            - name: ZOOKEEPER_CONNECT
              value: zookeeper
          image: chris/datagen
          name: datagen
      restartPolicy: Always
