apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: broker
  name: broker
spec:
  ports:
    - name: "6650"
      port: 6650
      targetPort: 6650
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: broker
