apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  containers:
    - args:
        - bash
        - -c
        - "bin/apply-config-from-env.py conf/zookeeper.conf && \n       bin/generate-zookeeper-config.sh conf/zookeeper.conf && \n       exec bin/pulsar zookeeper"
      env:
        - name: PULSAR_MEM
          value: -Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m
        - name: metadataStoreUrl
          value: zk:zookeeper:2181
      image: apachepulsar/pulsar:latest
      livenessProbe:
        exec:
          command:
            - bin/pulsar-zookeeper-ruok.sh
        failureThreshold: 30
        periodSeconds: 10
        timeoutSeconds: 5
      name: zookeeper
  restartPolicy: OnFailure
